# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51a6035e9be0f8a8a62f36afea070d2274b420b23e239501ebbfef8b29b48b6b950c435c519d1eab61eba488ed0d4c70f3dd47e638d7a024e7284a902d1866b3

test:
  secret_key_base: b7f331e749fca115a54b13ae91d2b5bdc8804e0e84be58ab6356a3f0ebacfb53a39b3fc3a38f4782202762a86dc09cebd9fe9f6f2f0e1af59346f26efa964149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
